### PR TITLE
remove protoc from lib-gha

### PR DESCRIPTION
**Pull request by na4ma4**
Nasty assumption that GHA is only Linux means it clobbers brew installed protobuf.

At least this will clobber it with a working version.

### CODE REVIEW

**Comment by na4ma4** [comment]
This is mostly for self-hosted runners, since github.com runners are fresh virtual machines each run.

It also saves bandwidth since it's not downloading every single time on a self-hosted runner.

**Comment by jmalloc** [comment]
Is there any reason that the "current version" matching logic need be for Linux only?

**Comment by na4ma4** [comment]
The recommended method of install is homebrew on macOS but you can just install the binary in the same method as the linux install.

Negatives are:
- need to detect if it was already installed with homebrew (simple symlink check would cover 99.9% of cases).
- do we run brew update/upgrade for the user ? that seems a bit invasive.
- if it's a version check against the releases, it's potentially not updated in brew so the update/upgrade might not make local==remote versions.

I figure if it's installed on macOS, then you're likely taking care of it with periodic running of brew update/upgrade.

I suppose checking for symlink and if it's not then assuming it's been previously installed with this method and updating could be OK.

**Comment by jmalloc** [comment]
The intent of this script was to always be running the latest. I would definitely prefer if it fetched the same version for both OSes.

I wonder if we can install it somewhere else (like under `artifacts/`, as we do with `protoc-gen-go`, etc) so that we simply don't collide with the system's installed version at all. I think this would only require two things:

- changing how `protoc` is executed in the `pkg-protobuf` `Makefile`
- possibly passing in an include path so that the `.proto` files that ship in this archive are found

It might even mean that we move this download logic into `pkg-protobuf` and avoid the CI-system-specific installation altogether

**Comment by na4ma4** [comment]
I made a PR against pkg-protobuf, so if you're happy I can drop this PR and do another one to remove protoc from here ?

**Comment by jmalloc** [comment]
Yeah nice, I think I prefer that approach - keeps behavior the same across CI systems and on local workstations :+1:

**Review by danilvpetrov — APPROVED** [review]

**Pull request merged**
